version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: camerrideshare_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0901
      POSTGRES_DB: camerrideshare
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - camerrideshare-net


volumes:
  postgres_data:

networks:
  camerrideshare-net:
